baseURL = "https://www.lorislab.org/"
languageCode = "en-us"
title = "lorislab"
theme = "hugo-stellar-theme"

[params]
  [params.header]
    title = "lorislab"
    description = 'Open source projects [@lorislaborg](http://github.com/lorislab)'
    image = "images/logo.svg"

  [[params.navigation]]
    name = "Introduction"
    href = "#intro"

  [params.intro]
    title = "Welcome! Let’s do some open source!"
    description = "The “what” and “why” of open source. So you’re thinking about getting started with open source? Congratulations! The world appreciates your contribution."
    image = "images/lorislab.jpeg"

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/lorislaborg"

      [[params.footer.social]]
        title = "Github"
        icon = "fa-github"
        link = "http://github.com/lorislab"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "mailto:team@lorislab.org"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "© lorislab.org"
