name: Github pages

on:
  push:
    branches:
      - master
    paths-ignore:
    - 'docs/**'       
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Install Hugo
      run: |
        curl https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.tar.gz -O -J -L
        mkdir tmp
        tar xfz hugo_0.58.3_Linux-64bit.tar.gz -C tmp
        mv tmp/hugo .
        rm -rf tmp
        rm hugo_0.58.3_Linux-64bit.tar.gz
    - name: Build pages
      run: ./hugo --gc --minify
    - name: Add the changes
      run: |        
        rm -rf docs
        mv public docs
        git config --global user.email "p6@lorislab.org"
        git config --global user.name "lorislab.org"
        git add docs/
        git commit -m "Build page"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PAGES_KEY }}
        
